const projects = [
  {
    id: "pankh",
    name: "PANKH",
    tagline: "Official Full Stack Event & Club Management Portal",
    thumbnail: "/pankh1.png",
    description:
      "A live Web Application currently being used by 1000+ students and faculty members. PANKH is an innovative Event & Club Management platform designed to modernize how events and clubs are managed at our college. The platform replaces traditional offline paperwork with a streamlined digital system, making event organization, participation and monitoring attendance more efficient than ever. Built by students, for students – PANKH is a step towards a smarter and more connected campus!",
    techStack: [
      "Next.js",
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/pankh1.png",
      "/pankh2.png",
      "/pankh3.png",
      "/pankh4.png",
      "/pankh5.png",
    ],
    github: "https://github.com/hemaxpatel/PANKH",
  },
  {
    id: "digital-rosca",
    name: "Digital ROSCA",
    tagline: "Full Stack ROSCA FinTech Web App",
    thumbnail: "/digital-rosca1.png",
    description:
      "Digital ROSCA is a web application designed to digitize and streamline the traditional Rotating Savings and Credit Association (ROSCA) system. It enables groups of users to collectively save money and provide credit in a transparent, secure, and automated manner.",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
      "Razorpay",
    ],
    images: [
      "/digital-rosca1.png",
      "/digital-rosca2.png",
      "/digital-rosca3.png",
      "/digital-rosca4.png",
    ],
    github: "https://github.com/hemaxpatel/Digital-ROSCA",
  },
  {
    id: "urban-axis",
    name: "Urban Axis",
    tagline: "Full Stack Real Estate Web App",
    thumbnail: "/urban-axis1.png",
    description:
      "Urban Axis is a modern real estate platform designed to streamline the process of buying, selling, and renting properties. It provides an intuitive interface for users to explore property listings, connect with sellers, and engage in real-time conversations with agents. Built to simplify real estate transactions – Urban Axis is the future of property buying and selling!",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Prisma ORM",
      "Socket.io",
      "Cloudinary",
    ],
    images: [
      "/urban-axis1.png",
      "/urban-axis2.png",
      "/urban-axis3.png",
      "/urban-axis4.png",
      "/urban-axis5.png",
    ],
    github: "https://github.com/hemaxpatel/Urban-Axis",
  },
  {
    id: "engineers-depot",
    name: "Engineer's Depot",
    tagline: "Full Stack Job Portal",
    thumbnail: "/engineers-depot1.png",
    description:
      "Engineer’s Depot is a full-stack MERN job portal that connects job seekers with recruiters. It simplifies the job search process by providing an intuitive platform to browse job listings, apply for positions, and communicate with recruiters in real-time. Empowering job seekers and recruiters – Engineer’s Depot is the future of job search and hiring!",
    techStack: [
      "React.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "Tailwind CSS",
      "Cloudinary",
    ],
    images: [
      "/engineers-depot1.png",
      "/engineers-depot2.jpg",
      "/engineers-depot3.png",
    ],
    github: "https://github.com/hemaxpatel/Engineers-Depot",
  },
  {
    id: "velocity",
    name: "Velocity",
    tagline: "Full Stack Project Management Tool",
    thumbnail: "/velocity1.jpg",
    description:
      "Velocity is a comprehensive project management tool designed to enhance team collaboration and streamline project workflows. It provides a user-friendly interface for managing tasks, tracking progress, and facilitating communication among team members. With features like task assignment, deadline tracking, and real-time updates, Velocity empowers teams to work more efficiently and effectively.",
    techStack: [
      "Next.js",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "Prisma ORM",
      "Redux Toolkit",
      "Tailwind CSS",
      "AWS (S3, EC2, RDS, Cognito, Lambda, Amplify, Api Gateway)",
    ],
    images: [
      "/velocity1.jpg",
      "/velocity2.jpg",
      "/velocity3.jpg",
      "/velocity4.jpg",
      "/velocity5.jpg",
      "/velocity6.jpg",
    ],
    github: "https://github.com/hemaxpatel/Velocity",
  },
  {
    id: "sabras",
    name: "Sabras",
    tagline: "Full Stack Subras Online Store",
    thumbnail: "/sabras1.jpg",
    description:
      "Sabras is a powerful and scalable full-stack e-commerce web application that provides a seamless online shopping experience for users and robust management tools for administrators. Designed with a focus on performance, usability, and security, Sabras demonstrates the core functionalities required to run a modern online store. Sabras enables customers to browse products, manage their cart, and complete secure purchases, while also offering administrators a dedicated dashboard to manage products, view orders, and oversee user activity. The application integrates real-time payment functionality and leverages modern technologies to create an efficient and user-friendly shopping experience.",
    techStack: ["React.js", "Node.js", "Express.js", "MongoDB", "Stripe"],
    images: [
      "/sabras1.jpg",
      "/sabras2.jpg",
      "/sabras3.jpg",
      "/sabras4.jpg",
      "/sabras5.jpg",
    ],
    github: "https://github.com/hemaxpatel/Sabras",
  },
];

export default projects;
